# Generated by Django 3.1.6 on 2021-02-05 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_hooks_delivery', '0002_auto_20190509_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='failedhook',
            name='event',
            field=models.CharField(db_index=True, editable=False, max_length=64),
        ),
    ]
